//import { Inter } from "next/font/google";
import "./globals.css";

import Layout from "./components/Layouts";
import { ApolloWrapper } from "./components/client";
import {AppProvider} from "./context/AppContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const title = "Welcome to Nextjs";

  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        <ApolloWrapper>
          <AppProvider>
            <Layout>
              <div className="container mx-auto px-4">{children}</div>
            </Layout>
          </AppProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
